baseurl: "http://besuto.me/"
languageCode: "ja"
title: "シババルーン"

Params:
  Author: "バルーンボーイ"
  Birth: "Dec. 26, 1990"
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "62012753"
  GravatarHash: "d9406594572d065298a1a4d1283f6d98"
  Twitter: "@besutome"
  Github: "besutome"
  ShowRelatedPost: True
  Disqus: "besutome"
  SyntaxHighlightTheme: "solarized_dark.min.css"
  description: "シババルーン"
  languageCode: "ja"
  countryCode: "ja"

Indexes:
  tag: "tags"

permalinks:
    post: /blog/:section/:filename/

# params.Twitter:
#   Account: "@jigyakkuma_"
#   Url: "https://twitter.com/jigyakkuma_"
# params.Github:
#   Url: "https://github.com/jigyakkuma"
#   UserName: "jigyakkuma"

MetadataFormat: "yaml"
