baseurl: "http://besuto.me"
languageCode: "ja"
title: "シババルーン"

Params:
  Author: "バルーンボーイ"
  Birth: "Dec. 26, 1990"
  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "UA-62012753-2"
  GravatarHash: "d9406594572d065298a1a4d1283f6d98"
  Twitter: "@besutome"
  Github: "besutome"
  ShowRelatedPost: True
  Disqus: "besutome"
  SyntaxHighlightTheme: "solarized_dark.min.css"
  description: "シババルーン"
  languageCode: "ja"
  countryCode: "ja"

Indexes:
  tag: "tags"

permalinks:
    post: /blog/:section/:filename/

MetadataFormat: "yaml"
